version: "3.8"

networks:
  fablo_basic:                # << we reuse the existing Fablo network
    external: true
    name: fablo_network_202507051259_basic   # <- keep this exact string

services:
  hyperledger-ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Map exposed port from Dockerfile
    networks:
      fablo_basic:
        aliases:              # guarantees DNS for these hostnames
          - ca.vaultx.example.com
          - peer0.vaultx.example.com
          - peer1.vaultx.example.com
    environment:
      SPRING_PROFILES_ACTIVE: test
      OTEL_SDK_DISABLED: "true"